export interface BookResults {
    title: string,
    subtitle: string,
    authors: string,
    publisher: string,
    publishedDate: string,
    description: string,
    industryIdentifiers: object[],
    pageCount: number,
    printType: string,
    catagories: string[],
    averageRating: number,
    ratingscount: number,
    maturityRating: string,
    language: string,
    id: string,
    link: string,
    thumbnail: string,
    images: string,
}
